# Generated by Django 3.1.1 on 2021-02-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210225_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project'},
        ),
        migrations.AddField(
            model_name='projects',
            name='is_site',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
